[book]
authors = ["Max Dobeck"]
language = "en"
multilingual = false
src = "src"
title = "Locale & Language"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
curly-quotes = true
copy-fonts = true
no-section-label = false
git-repository-url = "https://github.com/maxdobeck/books"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/maxdobeck/books/tree/main/sauce/locale-and-language/{path}"


[output.pdf]
