name: GH Pages Locale & Language Book

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install latest mdbook
        run: cargo install mdbook
      - name: Install mdbook-pdf backend
        run: cargo install mdbook-pdf
      - name: Build the Book
        run: mdbook build sauce/locale-and-language


