name: GH Pages Locale & Language Book

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
      - uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      # - name: Install Rust
      #   run: ci/install-rust.sh stable ${{ matrix.target }}
      # - name: Build asset
      #   run: ci/make-release-asset.sh ${{ matrix.os }} ${{ matrix.target }}
      # - name: Build locale-and-language Book
      #   run: cargo run -- build guide
      - name: Install latest mdbook
        run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo `pwd`/mdbook >> $GITHUB_PATH
      - name: build locale-and-language Book
        run: mdbook build sauce/locale-and-language


