name: Build Books

on:
  push:
    branches: [main]
    paths-ignore:
      - "docs/**"

  pull_request:
    branches: [main]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install latest mdbook
        run: cargo install mdbook
      - name: Install mdbook-pdf backend
        run: cargo install mdbook-pdf
      - name: Build the Book
        run: mdbook build sauce/locale-and-language

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v3
        with: 
          name: locale-and-language_PDF
          path: /sauce/locale-and-language/book/pdf/*.pdf
      - name: Upload HTML artifact
        uses: actions/upload-artifact@v3
        with: 
          name: locale-and-language_HTML
          path: /sauce/locale-and-language/book/html/*

